"use client";

import React from "react";
import { MasonryGrid } from "./MasonryGrid";
import { ProjectCard } from "@/components/project/ProjectCard";
import type { Project } from "@/lib/types";

// Mock data for feed
const mockProjects: Project[] = [
    {
        id: "1",
        user_id: "1",
        title: "Neon Pulse Animation",
        description: "A mesmerizing neon animation effect using pure CSS",
        html_content: null,
        css_content: null,
        js_content: null,
        thumbnail_url: null,
        thumbnail_aspect_ratio: 1.0,
        tags: ["animation", "css", "neon"],
        chat_messages: null,
        is_published: true,
        view_count: 1234,
        like_count: 567,
        collect_count: 45,
        comment_count: 89,
        share_count: 23,
        created_at: "2024-01-15",
        updated_at: "2024-01-15",
        creator: {
            id: "1",
            username: "creative_dev",
            display_name: "Creative Developer",
            avatar_url: null,
            bio: null,
            links: [],
            created_at: "",
            updated_at: "",
        },
    },
    {
        id: "2",
        user_id: "2",
        title: "Particle Storm",
        description: "Interactive particle system with canvas",
        html_content: null,
        css_content: null,
        js_content: null,
        thumbnail_url: null,
        thumbnail_aspect_ratio: 0.75,
        tags: ["particles", "canvas", "javascript"],
        chat_messages: null,
        is_published: true,
        view_count: 2345,
        like_count: 890,
        collect_count: 78,
        comment_count: 123,
        share_count: 45,
        created_at: "2024-02-01",
        updated_at: "2024-02-01",
        creator: {
            id: "2",
            username: "js_wizard",
            display_name: "JS Wizard",
            avatar_url: null,
            bio: null,
            links: [],
            created_at: "",
            updated_at: "",
        },
    },
    {
        id: "3",
        user_id: "3",
        title: "Glassmorphism Card",
        description: "Beautiful glassmorphism effect with blur",
        html_content: null,
        css_content: null,
        js_content: null,
        thumbnail_url: null,
        thumbnail_aspect_ratio: 1.2,
        tags: ["glassmorphism", "css", "card"],
        chat_messages: null,
        is_published: true,
        view_count: 3456,
        like_count: 1234,
        collect_count: 156,
        comment_count: 234,
        share_count: 67,
        created_at: "2024-02-15",
        updated_at: "2024-02-15",
        creator: {
            id: "3",
            username: "ui_master",
            display_name: "UI Master",
            avatar_url: null,
            bio: null,
            links: [],
            created_at: "",
            updated_at: "",
        },
    },
    {
        id: "4",
        user_id: "4",
        title: "Gradient Wave",
        description: "Smooth animated gradient background",
        html_content: null,
        css_content: null,
        js_content: null,
        thumbnail_url: null,
        thumbnail_aspect_ratio: 0.8,
        tags: ["gradient", "animation", "background"],
        chat_messages: null,
        is_published: true,
        view_count: 4567,
        like_count: 2345,
        collect_count: 234,
        comment_count: 345,
        share_count: 89,
        created_at: "2024-03-01",
        updated_at: "2024-03-01",
        creator: {
            id: "4",
            username: "color_queen",
            display_name: "Color Queen",
            avatar_url: null,
            bio: null,
            links: [],
            created_at: "",
            updated_at: "",
        },
    },
    {
        id: "5",
        user_id: "5",
        title: "3D Card Flip",
        description: "Interactive 3D card flip animation",
        html_content: null,
        css_content: null,
        js_content: null,
        thumbnail_url: null,
        thumbnail_aspect_ratio: 1.0,
        tags: ["3d", "animation", "interactive"],
        chat_messages: null,
        is_published: true,
        view_count: 5678,
        like_count: 3456,
        collect_count: 345,
        comment_count: 456,
        share_count: 123,
        created_at: "2024-03-15",
        updated_at: "2024-03-15",
        creator: {
            id: "5",
            username: "3d_artist",
            display_name: "3D Artist",
            avatar_url: null,
            bio: null,
            links: [],
            created_at: "",
            updated_at: "",
        },
    },
    {
        id: "6",
        user_id: "6",
        title: "Loading Spinner",
        description: "Minimal and smooth loading animation",
        html_content: null,
        css_content: null,
        js_content: null,
        thumbnail_url: null,
        thumbnail_aspect_ratio: 1.0,
        tags: ["loading", "animation", "minimal"],
        chat_messages: null,
        is_published: true,
        view_count: 6789,
        like_count: 4567,
        collect_count: 456,
        comment_count: 567,
        share_count: 156,
        created_at: "2024-04-01",
        updated_at: "2024-04-01",
        creator: {
            id: "6",
            username: "minimal_dev",
            display_name: "Minimal Dev",
            avatar_url: null,
            bio: null,
            links: [],
            created_at: "",
            updated_at: "",
        },
    },
];

export function FeedSection() {
    const [projects] = React.useState<Project[]>(mockProjects);

    return (
        <MasonryGrid projects={projects}>
            {(project) => <ProjectCard project={project} />}
        </MasonryGrid>
    );
}
